import datetime
import logging
from typing import Any, Dict, Optional, Union

import httpx

from src.schemas.incident_report import IncidentReport, IncidentReportCreate

logger = logging.getLogger(__name__)


def build_webhook_payload(
    report: Union[IncidentReportCreate, IncidentReport],
    incident_id: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Format an IncidentReport into a rich payload suitable for generic webhooks,
    Jira Service Management, and ServiceNow incident ingestion.
    """
    inc_id = getattr(report, "incident_id", incident_id or "inc_unknown")
    risk_upper = report.risk_level.upper()

    # Formatted description text for ticketing systems
    description_lines = [
        f"**Incident Summary:** {report.summary}",
        f"**Risk Level:** {risk_upper}",
        "",
        "**Assessed Risk Reasoning:**",
        report.risk_reasoning,
        "",
        "**Evidence-Supported Interpretations:**",
    ]
    for interp in report.possible_interpretations:
        description_lines.append(f"- {interp}")

    description_lines.append("")
    description_lines.append("**Recommended Defensive Actions:**")
    for action in report.recommended_actions:
        description_lines.append(f"- {action}")

    if report.citations:
        description_lines.append("")
        description_lines.append(f"**Knowledge Guidance Citations:** {', '.join(report.citations)}")

    description_text = "\n".join(description_lines)

    # Standardized payload
    payload: Dict[str, Any] = {
        "event": "security_incident_report",
        "incident_id": inc_id,
        "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "status": report.status,
        "risk_level": risk_upper,
        "summary": report.summary,
        "risk_reasoning": report.risk_reasoning,
        "possible_interpretations": report.possible_interpretations,
        "recommended_actions": report.recommended_actions,
        "citations": report.citations,
        "parser_statistics": report.parser_statistics,
        "observed_findings": report.observed_findings,
        # Jira compatible fields
        "jira": {
            "fields": {
                "project": {"key": "SEC"},
                "summary": f"[SecureOps Alert] {risk_upper}: {report.summary[:200]}",
                "description": description_text,
                "issuetype": {"name": "Security Incident"},
                "priority": {"name": "High" if risk_upper == "HIGH" else "Medium"},
            }
        },
        # ServiceNow compatible fields
        "servicenow": {
            "short_description": f"[SecureOps {inc_id}] {report.summary[:160]}",
            "description": description_text,
            "urgency": "1" if risk_upper == "HIGH" else ("2" if risk_upper == "MEDIUM" else "3"),
            "impact": "1" if risk_upper == "HIGH" else ("2" if risk_upper == "MEDIUM" else "3"),
            "category": "Security",
            "work_notes": f"Automated decision support triage generated by SecureOps Local (Model: {report.model_information.get('model', 'LocalLLM')})",
        },
    }

    return payload


def send_webhook(
    url: str,
    report: Union[IncidentReportCreate, IncidentReport],
    incident_id: Optional[str] = None,
    headers: Optional[Dict[str, str]] = None,
    timeout: float = 5.0,
) -> bool:
    """
    Deliver the incident payload to an external HTTP/HTTPS webhook endpoint (Jira/ServiceNow/Slack).
    """
    payload = build_webhook_payload(report, incident_id=incident_id)
    req_headers = {"Content-Type": "application/json", "User-Agent": "SecureOps-Local/1.0"}
    if headers:
        req_headers.update(headers)

    try:
        with httpx.Client(timeout=timeout) as client:
            resp = client.post(url, json=payload, headers=req_headers)
            if resp.status_code in (200, 201, 202, 204):
                logger.info(f"Successfully posted incident report to webhook '{url}' (HTTP {resp.status_code})")
                return True
            else:
                logger.warning(
                    f"Webhook '{url}' returned non-success HTTP status {resp.status_code}: {resp.text[:200]}"
                )
                return False
    except Exception as e:
        logger.error(f"Failed to deliver webhook to '{url}': {e}")
        return False
