"""Initial schema

Revision ID: 3abd85671fc1
Revises: 
Create Date: 2026-08-10 21:16:59.714362

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3abd85671fc1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('model_profile', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('raw_model_response', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_reports_id'), 'incident_reports', ['id'], unique=False)
    op.create_index(op.f('ix_incident_reports_status'), 'incident_reports', ['status'], unique=False)
    op.create_table('parsed_log_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('is_parsed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_log_lines_event_type'), 'parsed_log_lines', ['event_type'], unique=False)
    op.create_index(op.f('ix_parsed_log_lines_id'), 'parsed_log_lines', ['id'], unique=False)
    op.create_index(op.f('ix_parsed_log_lines_source_ip'), 'parsed_log_lines', ['source_ip'], unique=False)
    op.create_index(op.f('ix_parsed_log_lines_timestamp'), 'parsed_log_lines', ['timestamp'], unique=False)
    op.create_index(op.f('ix_parsed_log_lines_user'), 'parsed_log_lines', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsed_log_lines_user'), table_name='parsed_log_lines')
    op.drop_index(op.f('ix_parsed_log_lines_timestamp'), table_name='parsed_log_lines')
    op.drop_index(op.f('ix_parsed_log_lines_source_ip'), table_name='parsed_log_lines')
    op.drop_index(op.f('ix_parsed_log_lines_id'), table_name='parsed_log_lines')
    op.drop_index(op.f('ix_parsed_log_lines_event_type'), table_name='parsed_log_lines')
    op.drop_table('parsed_log_lines')
    op.drop_index(op.f('ix_incident_reports_status'), table_name='incident_reports')
    op.drop_index(op.f('ix_incident_reports_id'), table_name='incident_reports')
    op.drop_table('incident_reports')
    # ### end Alembic commands ###
