import datetime
from typing import List, Dict, Any

from pydantic import BaseModel, Field


class IncidentReportBase(BaseModel):
    status: str = Field(..., description="Status of the report generation, e.g., 'completed' or 'invalid_model_output'")
    summary: str = Field(..., description="High level summary of the incident")
    observed_findings: Dict[str, Any] = Field(..., description="Deterministic facts from the parser")
    possible_interpretations: List[str] = Field(..., description="Model generated interpretations")
    risk_level: str = Field(..., description="Assessed risk level")
    risk_reasoning: str = Field(..., description="Model reasoning for the risk level")
    recommended_actions: List[str] = Field(..., description="Recommended defensive actions")
    citations: List[str] = Field(..., description="List of context chunk IDs cited by the model")
    limitations: List[str] = Field(..., description="Limitations from both parser and model")
    parser_statistics: Dict[str, Any] = Field(..., description="Statistics generated by the parser")
    model_information: Dict[str, str] = Field(..., description="Details about the LLM provider and model used")
    performance_metrics: Dict[str, Any] = Field(..., description="Performance metrics of the generation")


class IncidentReportCreate(IncidentReportBase):
    pass


class IncidentReport(IncidentReportBase):
    id: int
    created_at: datetime.datetime
    incident_id: str

    class Config:
        from_attributes = True
